Repository owncloud/activity, pull requests merged in 2019-12, with the labels that each got.

#809 Minimize dev dependency install in drone
  .drone.star
  tests/Unit/ApiTest.php
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/ConsumerTest.php
  tests/Unit/Controller/ActivitiesTest.php
  tests/Unit/Controller/FeedTest.php
  tests/Unit/Controller/OCSEndPointTest.php
  tests/Unit/Controller/SettingsTest.php
  tests/Unit/DataDeleteActivitiesTest.php
  tests/Unit/DataHelperTest.php
  tests/Unit/DataTest.php
  tests/Unit/FilesHooksTest.php
  tests/Unit/Formatter/CloudIDFormatterTest.php
  tests/Unit/Formatter/FileFormatterTest.php
  tests/Unit/Formatter/UserFormatterTest.php
  tests/Unit/GroupHelperTest.php
  tests/Unit/HooksDeleteUserTest.php
  tests/Unit/MailQueueHandlerTest.php
  tests/Unit/Parameter/CollectionTest.php
  tests/Unit/Parameter/FactoryTest.php
  tests/Unit/Parameter/ParameterTest.php
  tests/Unit/PersonalTest.php
  tests/Unit/Template/RssTest.php
  tests/Unit/UserSettingsTest.php
  tests/Unit/ViewInfoCacheTest.php
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-Team

#810 Bump PHP version in composer.json
  composer.json
  composer.lock
Labels: 3 - To review, QA-Team

#813 Add sabre/xml to behat dependencies
  .drone.star
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#814 Increase wait-for-db timeout from 120 to 600 seconds
  .drone.star
Labels: 3 - To review, Drone, QA-Team

#815 Implement coding-standard 2.0.0
  tests/Unit/BackgroundJob/EmailNotificationTest.php
  tests/Unit/Controller/OCSEndPointTest.php
  tests/Unit/DataTest.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To review, QA-Team

#811 occ command to send all pending notifications
  appinfo/info.xml
  lib/Command/SendEmails.php
  lib/MailQueueHandler.php
  lib/Parameter/Factory.php
  tests/Unit/Command/SendEmailsTest.php
  tests/Unit/MailQueueHandlerTest.php
Labels: 3 - To review
