Repository owncloud/activity, pull requests merged in 2019-04, with the labels that each got.

#722 Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)
  composer.lock
Labels: 3 - To review

#723 phpunit enable failOnRisky
  phpunit.xml
Labels: 3 - To review, QA-Team

#711 use p() instead of echo
  templates/personal.php
Labels: 3 - To review, bug, p3-medium

#725 Revert "use p() instead of echo"
  templates/personal.php
Labels: 4 - To release
