Repository owncloud/activity, pull requests merged in 2019-06, with the labels that each got.

#736 Use standalone-chrome-debug:3.141.59-oxygen to get chrome 74
  .drone.yml
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#737 Adjust create user steps
  tests/acceptance/features/apiActivity/list.feature
  tests/acceptance/features/webUIActivityComments/comments.feature
  tests/acceptance/features/webUIActivityCreateUpdate/updateFilesFolder.feature
  tests/acceptance/features/webUIActivityDeleteRestore/delete.feature
  tests/acceptance/features/webUIActivityDeleteRestore/restore.feature
  tests/acceptance/features/webUIActivitySharingExternal/publicLinkShare.feature
  tests/acceptance/features/webUIActivitySharingExternal/sharingFederation.feature
  tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
  tests/acceptance/features/webUIActivityTags/tags.feature
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#738 Handle no longer existing groups
  CHANGELOG.md
  lib/Formatter/GroupFormatter.php
  tests/Unit/Formatter/GroupFormatterTest.php
Labels: 3 - To review

#743 Add acceptance tests for checking activity relating to users and groups that don't exist
  tests/acceptance/features/apiActivity/list.feature
  tests/acceptance/features/webUIActivitySharingInternal/sharingInternal.feature
Labels: 3 - To review, QA-Team, dev:acceptance-tests

#744 URL Formatter
  lib/Formatter/UrlFormatter.php
  lib/Parameter/Factory.php
  tests/Unit/Formatter/UrlFormatterTest.php
Labels: 3 - To review, enhancement
