Repository owncloud/activity, pull requests merged in 2020-04, with the labels that each got.

#851 [Tests-Only] Adjust tests to run with php 7.4
  tests/Unit/ConsumerTest.php
Labels: 3 - To review

#853 Implement phpunit v8
  tests/acceptance/features/bootstrap/WebUIActivityContext.php
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-Team

#855 Adjust unit tests for phpunit8
  tests/Unit/Command/SendEmailsTest.php
  tests/Unit/Controller/FeedTest.php
  tests/Unit/Controller/SettingsTest.php
  tests/Unit/NavigationTest.php
Labels: 4 - To release, QA-Team

#856 Ignore .phpunit.result.cache
  .gitignore
Labels: 4 - To release, QA-Team

#852 update karma and karma-jasmin
  package.json
  yarn.lock
Labels: 4 - To release

#857 Adjust drone pipelines for PHP 7.4
  .drone.star
Labels: 3 - To review, QA-Team
