Repository owncloud/activity, pull requests merged in 2020-12, with the labels that each got.

#904 [Tests-Only] improve starlark code for acceptance tests
  .drone.star
Labels: 3 - To review, Drone

#902 [Tests-Only][ci] dont run acceptance tests on CI after merge
  .drone.star
Labels: 3 - To review, QA-Team

#905 [tests-only] Run unit tests with mysql:8.0 in CI
  .drone.star
  sonar-project.properties
Labels: 3 - To review, QA-Team

#906 [Tests-Only][ci] purge the coverage cache after sonar analysis
  .drone.star
Labels: 4 - To release

#907 [tests-only] Add starlark code to handle the case when a repo has no code coverage tests
  .drone.star
Labels: 3 - To review, QA-Team

#908 [Tests-Only][CI] Set env vars to empty strings instead of None
  .drone.star
  sonar-project.properties
Labels: 4 - To release, Drone

#912 [tests-only] Bump minio/mc to latest docker tag
  .drone.star
Labels: 3 - To review, QA-Team

#913 [tests-only] skip core app-required scenarios
  .drone.star
Labels: 3 - To review, QA-Team

#914 [tests-only] Add option to run a pipeline in CI for both a PR and cron
  .drone.star
Labels: 3 - To review, QA-Team

#915 [tests-only] Adjust pullRequestAndCron logic in .drone.star
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 4 - To release, QA-Team

#916 [docs-only] SonarCloud badges
  README.md
Labels: 3 - To review
