Repository owncloud/activity, pull requests merged in 2020-02, with the labels that each got.

#831 Update starlark code for Oracle and X-Forwarded-For
  .drone.star
Labels: 3 - To review, Drone, QA-Team

#833 Add a config option to send notifications ASAP
  lib/Controller/Settings.php
  lib/UserSettings.php
  templates/personal.php
  tests/Unit/Controller/SettingsTest.php
Labels: 3 - To review

#834 [Tests-only] Run core tests with activity enabled
  .drone.star
  Makefile
Labels: 4 - To release, QA-Team, dev:acceptance-tests

#837 Test with guzzle6
  vendor-bin/behat/composer.json
Labels: 2 - Developing

#838 Correct the Oracle Db auth in .drone.star
  .drone.star
Labels: 3 - To review, Drone, QA-Team
