Repository owncloud/activity, pull requests merged in 2021-11, with the labels that each got.

#1027 [tests-only] Update to latest .drone.star code
  .drone.star
Labels: QA-Team

#1018 Implement activities for rename and move actions
  css/style.css
  img/move.svg
  img/rename.svg
  js/activitytabview.js
  js/formatter.js
  js/script.js
  lib/AppInfo/Application.php
  lib/Extension/Files.php
  lib/FilesHooks.php
  lib/FilesHooksStatic.php
  tests/Unit/FilesHooksTest.php
  tests/acceptance/features/apiActivity/list.feature
  tests/acceptance/features/bootstrap/ActivityContext.php
Labels: 3 - To review

#1030 Added scenario to check activity from public user
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiActivity/list.feature
  tests/acceptance/features/bootstrap/ActivityContext.php
Labels: QA-Team

#1031 Implement a global setting to enable or disable move/rename-activities
  lib/AppInfo/Application.php
  lib/Controller/Settings.php
  lib/FilesHooks.php
  tests/Unit/FilesHooksTest.php
  tests/acceptance/features/apiActivity/list.feature
  tests/acceptance/features/bootstrap/ActivityContext.php
Labels: php
